### PR TITLE
Update to GNOME 41

### PR DESCRIPTION
**Pull request by Eonfge**
Also include all dependencies

### CODE REVIEW

**Comment by Eonfge** [comment]
@muelli Could you give this a look. Think I fixed every outstanding issue

**Comment by muelli** [comment]
LGTM!

If you're looking into a new side quest, I recommend adding flatpak-external-data-checker support to the dependencies, so that the bot can update them.

**Comment by rolandlo** [comment]
Hmm, the update to Gnome 41 seems to have broken plugins that use lua-lgi. Was that considered acceptable? 
The error message is different than it was with Gnome 40 before the update though:
```
(xournalpp:2): GLib-GObject-CRITICAL **: 20:47:46.199: g_boxed_type_register_static: assertion 'g_type_from_name (name) == 0' failed

(xournalpp:2): GLib-CRITICAL **: 20:47:46.199: g_once_init_leave: assertion 'result != 0' failed

(xournalpp:2): GLib-GObject-CRITICAL **: 20:47:46.199: g_boxed_type_register_static: assertion 'g_type_from_name (name) == 0' failed

(xournalpp:2): GLib-CRITICAL **: 20:47:46.199: g_once_init_leave: assertion 'result != 0' failed

(xournalpp:2): Gtk-ERROR **: 20:47:46.200: GTK 2/3 symbols detected. Using GTK 2/3 and GTK 4 in the same process is not supported
```

**Comment by Technius** [comment]
Gnome >= 40 is on GTK4. I'm not sure where lua-lgi is packaged--is it from your own system?

**Comment by Technius** [comment]
Nevermind, I just saw that it's compiled in the manifest.

**Comment by Eonfge** [comment]
:thinking: 

There are a few things to clear up; GNOME 40 and GNOME 41 both also contain all GTK 3 components. GTK 2 is deprecated and no longer included by default, but using GTK 3 is still totally fine.

As for the issues with plugins, I did not know with which plug-ins to test. I tried a few quickly and they seemed to work. What plug-in is giving you issues? 

The reason that i made this merge request, is because 3.38 is now old and will no longer receive any security updates. We should also soon update the TexLive dependencies, which I forgot in this initial pull request.


Perhaps this issue is best reported over at; https://github.com/pavouk/lgi

**Comment by Technius** [comment]
The most important one is "Show font size migration dialog" (via MigrateFontSizes plugin). I'm able to reproduce @rolandlo's crash by clicking on that menu item.

**Comment by muelli** [comment]
hm. How important is this lua breakage? should we roll the change back for the time this is being investigated?

**Comment by rolandlo** [comment]
> 
> Perhaps this issue is best reported over at; https://github.com/pavouk/lgi

It has already been reported there a while ago, as [linked to](https://github.com/pavouk/lgi/issues/226
) in the comment that got removed in this PR:
```
# Lua-lgi does not work yet with Gtk 4 / Gnome 40, see https://github.com/pavouk/lgi/issues/226
```

**Comment by rolandlo** [comment]
> hm. How important is this lua breakage? should we roll the change back for the time this is being investigated?

Considering that those who need the Font Size migration plugin to migrate font sizes (or use some other plugin using Lua `lgi`) can just use the AppImage or the snap package, it is not that important. As long as we don't get too many complaints we can wait for a fix from the `lgi` developers, I think.

**Pull request merged**
