### PR TITLE
Update to GNOME 45

### PR DESCRIPTION
**Pull request by Eonfge**

### CODE REVIEW

**Comment by rolandlo** [comment]
Looks like we must bundle GtkSourceView 4 (as in https://gitlab.gnome.org/GNOME/gnome-boxes/-/merge_requests/578/diffs), since Gnome 45 dropped it.

**Comment by Eonfge** [comment]
> Looks like we must bundle GtkSourceView 4 (as in https://gitlab.gnome.org/GNOME/gnome-boxes/-/merge_requests/578/diffs), since Gnome 45 dropped it.

Where do we actually use that? Application starts without it and I can open a PDF.

**Comment by rolandlo** [comment]
It's for the LaTeX editor:
grafik


See also the LaTeX tab in the preferences:
grafik

When Xournal++ is compiled without GtkSourceView those features (like syntax highlighting, wrap, line numbers etc.) are disabled.

**Comment by rolandlo** [comment]
The GtkSourceView styling works now. I do get some error messages though when using the LaTeX tool

grafik

Also the background for the LaTeX formula is dark (instead of light) now, which doesn't go well with dark text color.

grafik

instead of this:

grafik

**Comment by Eonfge** [comment]
The background colour changing, is something that Upstream will have to look into. Not something you can really affect on a packaging level.

**Comment by Eonfge** [comment]
My apologies for referencing you in the third person: You're upstream. 

But yeah, it seems that something goes wrong with parsing the theme and you'll have to look in the application itself to see how that happens.

**Comment by rolandlo** [comment]
The background color changing shouldn't have something to do with GtkSourceView. Xournal++ decides on base of the contrast of the text color with black/white whether it renders the background of the LaTeX formula black or white (using Cairo). 

https://github.com/xournalpp/xournalpp/blob/40fcf731ba30e5890dae358fd0d896bc2ee2254e/src/core/control/LatexController.cpp#L197-L202

https://github.com/xournalpp/xournalpp/blob/40fcf731ba30e5890dae358fd0d896bc2ee2254e/src/core/gui/dialog/LatexDialog.cpp#L212-L214

I currently don't see, what could possibly go wrong here (it works fine in non-flatpak versions), but I agree, this doesn't look like a packaging issue.

**Comment by rolandlo** [comment]
The old version had the same problem. So I'm merging.

**Comment by rolandlo** [comment]
> The background color changing shouldn't have something to do with GtkSourceView. Xournal++ decides on base of the contrast of the text color with black/white whether it renders the background of the LaTeX formula black or white (using Cairo).
> 
> https://github.com/xournalpp/xournalpp/blob/40fcf731ba30e5890dae358fd0d896bc2ee2254e/src/core/control/LatexController.cpp#L197-L202
> 
> https://github.com/xournalpp/xournalpp/blob/40fcf731ba30e5890dae358fd0d896bc2ee2254e/src/core/gui/dialog/LatexDialog.cpp#L212-L214
> 
> I currently don't see, what could possibly go wrong here (it works fine in non-flatpak versions), but I agree, this doesn't look like a packaging issue.

Here I looked into the wrong branch (`master` instead of `release-1.2`). Looking closer into it, I discovered the problem. A fix is available in https://github.com/xournalpp/xournalpp/pull/5307 and should be part of the upcoming 1.2.3 release.

**Pull request merged**
