### PR TITLE
Update texlive extension to 22.08

### PR DESCRIPTION
**Pull request by Eonfge**
@muelli Do you have any experience testing this?

### CODE REVIEW

**Comment by Eonfge** [comment]
Runs for me, but don't have anything to test it with.

**Comment by muelli** [comment]
> @muelli Do you have any experience testing this?

I don't :(

But I guess the current state, i.e. with 21.08, is more broken than the proposed state (with 22.08) can be, given that the runtime is now GNOME 43.

**Comment by Eonfge** [comment]
It works with GNOME 43 and Runtime 21.08, I did test that! But yeah, let's just roll this out. Perhaps we can find somebody down the line who can help with the whole texlive thing.

**Comment by rolandlo** [comment]
I have already made some tests with the 22.08 runtime. Seems to work great. All LaTeX formulas from [the guide](https://xournalpp.github.io/guide/tools/latex/) still work.

**Comment by Eonfge** [comment]
:scream: Latex is total gibberish... Next, we'll have to support Elvish. :rofl:

**Pull request merged**
